title: My Learning Journey
description: Putting the experiences on "paper"
theme: just-the-docs

url: https://zapatify.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
